on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set Dotenv
      run: cp /home/williancard/.env-reference ./.env

    - name: Docker down
      run: docker-compose down

    - name: Build and start Docker containers
      run: docker-compose up --build -d
